- name: Copy App
  copy:
    src: "{{ playbook_dir | dirname }}/src/app"
    dest: /usr/bin/app
    owner: root
    group: root
    mode: '0711'

- name: Start App
  shell: /usr/bin/app >/dev/null 2>&1 &
